### ISSUE TITLE
Passing the parcelable passport object between activity failed

### ISSUE THREAD

**Issue by RayRX16** [jllarraz/AndroidPassportReader#18]
Hello Jose,
I have tried to pass the parcelable passport object between activity, but it failed when writeToParcel() in VerificationStatus was called.
The logcat said that the attribute sac in VerificationStatus was null and sac!!.name occurred NullPointerException.
I tried to fix it by using sac?.name, but then the app crashed without useful debug info.
I think there may be some bugs in the parcelable code about passport object.
Can you help to solve it?

**Comment by jllarraz** [comment]
it should be fixed now

**Comment by RayRX16** [comment]
Excuse me.  I use the latest code but still met the problem. 
Can you check again?

**Comment by RayRX16** [comment]
After doing some experiments, I guess that passing large bitmap in the passport between activities may cause the crash because the data attached to the intent has a size limitation.

**Comment by jllarraz** [comment]
Hi

Yes that's the reason why I am not passing it as a Parcelable in the
example. Anyway the right way to do it is to persist the picture to a
folder and get the URI, and the save that URI into the Parcelable object.
But I just didn't implement it because it's out of the scope of the example.

Best regards

**Comment by RayRX16** [comment]
Because I am not familiar with big file transferring between activities, I ignore the this condition.
Anyway, your project is really helpful. Thanks.
